### PR TITLE
Update topic-3.md with ZH's presentation attached

### PR DESCRIPTION
**Pull request by zachary0249**

### CODE REVIEW

**Comment by drmajidbabaei** [comment]
Hi Zach (@zachary0249) , 

The summary is supposed to reflect your understanding of the paper, the proposed approach, obtained results, and discussion. To get a better idea of the kind of summary I am expecting please check out these two samples:
https://ecse437.majidbabaei.com/presentations/requesting-time-off/topic-1-taken
https://ecse437.majidbabaei.com/presentations/requesting-time-off/topic-2-taken

**Comment by drmajidbabaei** [comment]
@zachary0249 would you please address the issue I mentioned as soon as you get some time.

**Comment by zachary0249** [comment]
Dear Prof,Apologies for the delay, it will be done by EOD.Thank you,ZachOn Oct 16, 2023, at 13:30, Dr. Majid Babaei ***@***.***> wrote:﻿
@zachary0249 would you please address the issue I mentioned as soon as you get some time.

**Review by drmajidbabaei — APPROVED** [review]
Thanks @zachary0249 it looks good 👍

**Pull request merged**
